# Generated by Django 4.2 on 2025-12-09 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Jarayon (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan sana')),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Test urinishi', 'verbose_name_plural': 'Test urinishi'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fikr', 'verbose_name_plural': 'Fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'Talaba jarayoni', 'verbose_name_plural': 'Talabalar jarayoni'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=500, verbose_name='Javob matni'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='Ota kategoriya'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_available',
            field=models.BooleanField(default=True, verbose_name='Sertifikat beriladi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Chegirma narxi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1, verbose_name='Davomiyligi (hafta)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilgan'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='uz', max_length=50, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.JSONField(default=list, verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='courses/thumbnails/', verbose_name='Kurs rasmi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Kurs nomi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy davomiylik (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_lectures',
            field=models.PositiveIntegerField(default=0, verbose_name='Darslar soni'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Talabalar soni'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_preview',
            field=models.URLField(blank=True, null=True, verbose_name='Preview video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_learn',
            field=models.JSONField(default=list, verbose_name="Nima o'rganasiz"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matnli kontent'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Majburiy'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Preview dars'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Maqola'), ('quiz', 'Test'), ('assignment', 'Vazifa')], default='video', max_length=20, verbose_name='Dars turi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Dars nomi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_duration',
            field=models.PositiveIntegerField(default=0, help_text='Soniyalarda', verbose_name='Video davomiyligi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Davomiyligi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Modul nomi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Tushuntirish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Bir javobli'), ('multiple', "Ko'p javobli"), ('text', 'Matnli javob')], default='single', max_length=20, verbose_name='Savol turi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(default=3, verbose_name='Urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='Dars'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=70, verbose_name="O'tish balli"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Test nomi'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Javoblar'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.IntegerField(verbose_name="To'g'ri javoblar"),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name="O'tdi"),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.IntegerField(verbose_name='Sarflangan vaqt'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(verbose_name='Umumiy savollar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Fikr'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan sotib olish'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tugallangan'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='last_position_seconds',
            field=models.IntegerField(default=0, verbose_name='Oxirgi pozitsiya'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Dars'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='courses_cou_teacher_ef24fb_idx'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
