# Generated by Django 4.2 on 2026-01-31 07:31

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0004_remove_module_duration_minutes_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, help_text="Foydalanuvchining to'liq ismi", max_length=255, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, help_text='Telefon raqami +998XXXXXXXXX formatida', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+?998?\\d{9}$')], verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('admin', 'Administrator')], default='student', help_text='Foydalanuvchi roli', max_length=20, verbose_name='Rol')),
                ('user_code', models.CharField(blank=True, help_text='Dashboard uchun 4 xonali foydalanuvchi kodi', max_length=4, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, help_text="Qisqacha ma'lumot", verbose_name='Biografiya')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Mutaxassislik')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Ish tajribasi (yil)')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting')),
                ('total_students', models.IntegerField(default=0, verbose_name='Jami talabalar')),
                ('total_courses', models.IntegerField(default=0, verbose_name='Jami kurslar')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soatlik tarif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ijtimoiy tarmoq havolalari', verbose_name='Ijtimoiy tarmoqlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi Profil",
                'verbose_name_plural': "O'qituvchi Profillari",
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name="Ta'lim darajasi")),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Maktab nomi')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Sinf')),
                ('total_points', models.IntegerField(default=0, verbose_name='Jami ballar')),
                ('level', models.IntegerField(default=1, verbose_name='Daraja')),
                ('total_watch_time', models.IntegerField(default=0, verbose_name='Jami tomosha vaqti (daqiqa)')),
                ('learning_goals', models.TextField(blank=True, verbose_name="O'rganish maqsadlari")),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='Qiziqishlar')),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_by_students', to='courses.course', verbose_name='Tugatilgan kurslar')),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_students', to='courses.course', verbose_name="Ro'yxatdan o'tgan kurslar")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profil',
                'verbose_name_plural': 'Student Profillari',
            },
        ),
    ]
