# Generated by Django 4.2 on 2026-02-05 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='medium', max_length=10)),
                ('word_count', models.IntegerField(default=0, verbose_name="So'zlar soni")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Typing Test',
                'verbose_name_plural': 'Typing Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField(verbose_name='WPM (Words Per Minute)')),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Aniqlik (%)')),
                ('time_taken', models.IntegerField(verbose_name='Vaqt (soniya)')),
                ('errors', models.IntegerField(default=0, verbose_name='Xatolar soni')),
                ('is_arena', models.BooleanField(default=False, verbose_name='Arena rejimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='typing_test.typingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typing Result',
                'verbose_name_plural': 'Typing Results',
                'ordering': ['-wpm', '-accuracy'],
            },
        ),
        migrations.CreateModel(
            name='ArenaLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_wpm', models.IntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('total_arena_tests', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_rank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena Leaderboard',
                'verbose_name_plural': 'Arena Leaderboard',
                'ordering': ['-best_wpm', '-best_accuracy'],
            },
        ),
        migrations.AddIndex(
            model_name='typingresult',
            index=models.Index(fields=['-wpm', '-accuracy'], name='typing_test_wpm_6b0a42_idx'),
        ),
        migrations.AddIndex(
            model_name='typingresult',
            index=models.Index(fields=['user', '-created_at'], name='typing_test_user_id_a1b1e9_idx'),
        ),
    ]
