# Generated by Django 4.2 on 2026-02-10 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typing_test', '0002_alter_arenaleaderboard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arenaleaderboard',
            options={'ordering': ['-best_wpm', '-best_accuracy'], 'verbose_name': 'Arena Leaderboard', 'verbose_name_plural': 'Arena Leaderboard'},
        ),
        migrations.AlterModelOptions(
            name='typingresult',
            options={'ordering': ['-wpm', '-accuracy'], 'verbose_name': 'Typing Result', 'verbose_name_plural': 'Typing Results'},
        ),
        migrations.AlterModelOptions(
            name='typingtest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Typing Test', 'verbose_name_plural': 'Typing Tests'},
        ),
        migrations.AddField(
            model_name='arenaleaderboard',
            name='best_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='arenaleaderboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arenaleaderboard',
            name='total_arena_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='accuracy',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Aniqlik (%)'),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='errors',
            field=models.IntegerField(default=0, verbose_name='Xatolar soni'),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='is_arena',
            field=models.BooleanField(default=False, verbose_name='Arena rejimi'),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='time_taken',
            field=models.FloatField(default=0.0, verbose_name='Vaqt (soniya)'),
        ),
        migrations.AddField(
            model_name='typingresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typingtest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='typingtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typingtest',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=10),
        ),
        migrations.AddField(
            model_name='typingtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typingtest',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arenaleaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_rank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='typing_test.typingtest'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='wpm',
            field=models.FloatField(default=0.0, verbose_name='WPM (Words Per Minute)'),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='typingresult',
            index=models.Index(fields=['-wpm', '-accuracy'], name='typing_test_wpm_6b0a42_idx'),
        ),
        migrations.AddIndex(
            model_name='typingresult',
            index=models.Index(fields=['user', '-created_at'], name='typing_test_user_id_a1b1e9_idx'),
        ),
    ]
