# Generated by Django 4.2 on 2026-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Matn')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Asosiy rasm')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Teglar')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Yoqtirishlar soni')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Yoqtirmasliklar soni')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO sarlavha')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='SEO tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt')),
            ],
            options={
                'verbose_name': 'Blog maqola',
                'verbose_name_plural': 'Blog maqolalar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reaktsiya',
                'verbose_name_plural': 'Reaktsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
