# Generated by Django 4.2 on 2026-02-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typing_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arenaleaderboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typingresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typingtest',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='typingresult',
            name='typing_test_wpm_6b0a42_idx',
        ),
        migrations.RemoveIndex(
            model_name='typingresult',
            name='typing_test_user_id_a1b1e9_idx',
        ),
        migrations.RemoveField(
            model_name='arenaleaderboard',
            name='best_accuracy',
        ),
        migrations.RemoveField(
            model_name='arenaleaderboard',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='arenaleaderboard',
            name='total_arena_tests',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='is_arena',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='typingtest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='typingtest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='typingtest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='typingtest',
            name='word_count',
        ),
        migrations.AlterField(
            model_name='arenaleaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_test.typingtest'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='wpm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
