# Generated by Django 4.2 on 2026-03-03 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typing_test', '0003_alter_arenaleaderboard_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='typingresult',
            name='typing_test_wpm_6b0a42_idx',
        ),
        migrations.RemoveField(
            model_name='typingresult',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='arenaleaderboard',
            name='best_wpm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arenaleaderboard',
            name='total_arena_tests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arenaleaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='accuracy',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Aniqlik (%)'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='is_arena',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='time_taken',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vaqt (soniya)'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='wpm',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='WPM'),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='typingtest',
            name='word_count',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddIndex(
            model_name='typingresult',
            index=models.Index(fields=['-wpm'], name='typing_test_wpm_b61835_idx'),
        ),
    ]
