# Generated by Django 4.2 on 2026-04-04 16:49

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+?998?\\d{9}$')], verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('admin', 'Administrator')], default='student', max_length=20, verbose_name='Rol')),
                ('user_code', models.CharField(blank=True, help_text='Dashboard uchun 4 xonali foydalanuvchi kodi', max_length=4, null=True, unique=True)),
                ('father_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='Tuman')),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('parent_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Ota-ona ismi')),
                ('parent_phone', models.CharField(blank=True, default='', max_length=13, verbose_name='Ota-ona telefoni')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografiya')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram username')),
                ('telegram_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram ID')),
                ('class_room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sinf')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh')),
                ('points', models.IntegerField(default=0, verbose_name='Ballar')),
                ('badges', models.JSONField(blank=True, default=list, verbose_name='Nishonlar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Mutaxassislik')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Ish tajribasi (yil)')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting')),
                ('total_students', models.IntegerField(default=0, verbose_name='Jami talabalar')),
                ('total_courses', models.IntegerField(default=0, verbose_name='Jami kurslar')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soatlik tarif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ijtimoiy tarmoq havolalari', verbose_name='Ijtimoiy tarmoqlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi Profil",
                'verbose_name_plural': "O'qituvchi Profillari",
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name="Ta'lim darajasi")),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Maktab nomi')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Sinf')),
                ('total_points', models.IntegerField(default=0, verbose_name='Jami ballar')),
                ('level', models.IntegerField(default=1, verbose_name='Daraja')),
                ('total_watch_time', models.IntegerField(default=0, verbose_name='Jami tomosha vaqti (daqiqa)')),
                ('learning_goals', models.TextField(blank=True, verbose_name="O'rganish maqsadlari")),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='Qiziqishlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profil',
                'verbose_name_plural': 'Student Profillari',
            },
        ),
    ]
