# Generated by Django 4.2 on 2025-12-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_enrollment_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Kurs rasmi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_learn',
            field=models.JSONField(blank=True, default=list, verbose_name="Nima o'rganasiz"),
        ),
    ]
