# Generated by Django 4.2 on 2026-04-04 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Kurs rasmi')),
                ('video_preview', models.URLField(blank=True, null=True, verbose_name='Preview video')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20, verbose_name='Daraja')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Narx (so'm)")),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Chegirma narxi')),
                ('duration_weeks', models.PositiveIntegerField(default=1, verbose_name='Davomiyligi (hafta)')),
                ('total_lectures', models.PositiveIntegerField(default=0, verbose_name='Darslar soni')),
                ('total_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Umumiy davomiylik (daqiqa)')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('what_you_learn', models.JSONField(blank=True, default=list, verbose_name="Nima o'rganasiz")),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Teglar')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Talabalar soni')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bestseller')),
                ('language', models.CharField(default='uz', max_length=50, verbose_name='Til')),
                ('certificate_available', models.BooleanField(default=True, verbose_name='Sertifikat beriladi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Jarayon (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan sana')),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars nomi')),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('article', 'Maqola'), ('quiz', 'Test'), ('assignment', 'Vazifa')], default='video', max_length=20, verbose_name='Dars turi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='Soniyalarda', verbose_name='Video davomiyligi')),
                ('content', models.TextField(blank=True, verbose_name='Matnli kontent')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Fayl')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Preview dars')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Modul nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('single', 'Bir javobli'), ('multiple', "Ko'p javobli"), ('text', 'Matnli javob')], default='single', max_length=20, verbose_name='Savol turi')),
                ('points', models.IntegerField(default=1, verbose_name='Ball')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('passing_score', models.IntegerField(default=70, verbose_name="O'tish balli")),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('attempts_allowed', models.IntegerField(default=3, verbose_name='Urinishlar soni')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball')),
                ('total_questions', models.IntegerField(verbose_name='Umumiy savollar')),
                ('correct_answers', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('time_taken_seconds', models.IntegerField(verbose_name='Sarflangan vaqt')),
                ('answers', models.JSONField(default=dict, verbose_name='Javoblar')),
                ('is_passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishi',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baholash')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Fikr')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Tasdiqlangan sotib olish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugallangan')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('last_position_seconds', models.IntegerField(default=0, verbose_name='Oxirgi pozitsiya')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Talaba jarayoni',
                'verbose_name_plural': 'Talabalar jarayoni',
            },
        ),
    ]
