# Generated by Django 4.2 on 2025-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_enrolled', 'Kursga yozilindi'), ('lesson_completed', 'Dars tugallandi'), ('certificate_issued', 'Sertifikat berildi'), ('payment_successful', "To'lov muvaffaqiyatli"), ('new_message', 'Yangi xabar'), ('course_updated', 'Kurs yangilandi')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
