# Generated by Django 4.2 on 2026-04-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat xonasi',
                'verbose_name_plural': 'Chat xonalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('file', 'Fayl'), ('voice', 'Ovozli xabar'), ('video', 'Video xabar')], default='text', max_length=10, verbose_name='Xabar turi')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Davomiylik (soniya)')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('is_edited', models.BooleanField(default=False, verbose_name='Tahrirlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reaction',
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'verbose_name': 'Pin qilingan xabar',
                'ordering': ['-pinned_at'],
            },
        ),
    ]
