# Generated by Django 4.2 on 2026-05-27 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_messagereaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'verbose_name': 'Reaksiya', 'verbose_name_plural': 'Reaksiyalar'},
        ),
        migrations.AlterModelOptions(
            name='pinnedmessage',
            options={'ordering': ['-pinned_at'], 'verbose_name': 'Pinlangan xabar', 'verbose_name_plural': 'Pinlangan xabarlar'},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Guruh chat'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Guruh nomi'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Ovozli/video xabar davomiyligi (soniya)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinnedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_5feac5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_read', 'is_deleted'], name='chat_messag_room_id_62e425_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
    ]
